name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

  my_second_job:
      name: My second job
      runs-on: ubuntu-latest
        steps:
         - name: Run a multi-line script
        run: |
          sudo apt-get install -y dos2unix
          # git clone https://github.com/rentianyu/Ad-set-hosts.git
          # cd Ad-set-hosts
          pwd
          git config --local user.email "1782898491@qq.com"
          git config --local user.name "rentianyu"
          bash update_action.sh

  my_third_job:
      name: My third job
      runs-on: ubuntu-latest
        steps:
        - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
