name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          sudo apt-get install -y dos2unix
          git clone https://github.com/rentianyu/Ad-set-hosts.git
          cd Ad-set-hosts
          git config --global user.email "1782898491@qq.com"
          git config --global user.name "rentianyu"
          bash update_action.sh


      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}